### PR TITLE
Collapsable and redesigned state inspector

### PR DESCRIPTION
**Pull request by Akryum**
- Sections in state inspector are now collapsable
- Shift + Click and Ctrl + Click to expand/collapse all sections
- They are also redesigned
- Some style refactoring
- Vuex history items have now the same height as Events history items

vue-devtool-collpase-data-sections

### CODE REVIEW

**Comment by posva** [comment]
Looks nice, I prefer it to #392

**Comment by posva** [comment]
Testing on mac, it doesn't seem to expand or collapse all. Also, I would update the popover to display cmd or the unicode symbol

**Comment by Akryum** [comment]
Fixed by https://github.com/Akryum/vue-devtools/commit/5b7745d5d79f7e12341f5072d4ad3f2061c59ae2

**Comment by posva** [comment]
Works nicely now!

Some extra thoughts for the future:

- remove the pointer cursor on properties (something like `.key:not(.abstract), .colon, .value {cursor: initial;}`
- make some of the tree parts non selectable (this may have some edge cases

**Pull request merged**
