### PR TITLE
Export/Import state

### PR DESCRIPTION
**Pull request by zigomir**
Here is implementation of idea from [issue 101](https://github.com/vuejs/vue-devtools/issues/101).
It's still a bit rough, but I think it can be super useful. I still need to try it out on larger objects.

vuex dev tools export import state

### CODE REVIEW

**Comment by yyx990803** [comment]
I think the import should also be a button, and have a popup textarea only when clicked.

**Comment by zigomir** [comment]
@yyx990803 I updated code and gif to use popup. Not sure if we want any close buttons or anything. It now closes on ESC key or clicking on `paste` button again.

**Comment by yyx990803** [comment]
niceeeee

**Comment by yyx990803** [comment]
Great job - I will add a few styling tweaks before doing a release.

**Comment by yyx990803** [comment]
btw would be nice to add a few assertions in the test: https://github.com/vuejs/vue-devtools/blob/master/test/specs/test.js

**Pull request merged**
