### PR TITLE
new gifs for readme

### PR DESCRIPTION
**Pull request by crswll**
If you need anything adjusted let me know.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks @crswll - in fact I have quite a few more changes to the Vuex tab lined up, so we will need to make new gifs after the new release is settled, hope you don't mind!

**Comment by crswll** [comment]
I don't mind at all. Just let me know whenever.

**Comment by tomByrer** [comment]
You might be able to squeeze 50k or so out of the GIFs if you use ImageOptim or the like.  Since I use Windows, FileOptimizer works for all file formats...
Got to save bandwidth for those cat videos!

**Comment by yyx990803** [comment]
Okay, changes are done. Note that the Vuex tab behavior has changed: now when you click on a mutation, it only inspects its state but not instantly time-travels to it. You will need to explicitly click the time travel button to do that.

**Comment by crswll** [comment]
Awesome. I'll try to knock it out at lunch. I take a look real quick and I get an error when I try to switch to the Vuex tab.

screen shot 2017-01-05 at 10 47 47 am

Also the test is failing (imagine that's related).

screen shot 2017-01-05 at 10 50 37 am

**Comment by yyx990803** [comment]
Do a fresh npm install - this was an issue fixed in latest `vue-template-es2015-compiler`.

**Comment by crswll** [comment]
new gifs are now in there

**Comment by yyx990803** [comment]
Thanks! 👍

**Comment by yyx990803** [comment]
For some reason GitHub seems to be caching the images...

**Comment by crswll** [comment]
I'm seeing the new ones at https://github.com/vuejs/vue-devtools

**Pull request merged**
