### PR TITLE
Feature/clear all messages vuex events

### PR DESCRIPTION
**Pull request by mikaelhadler**

### CODE REVIEW

**Comment by Akryum** [comment]
What's is the difference with the `Commit All` button?

**Comment by mikaelhadler** [comment]
@Akryum `` `` ClearAll`` has not attempted to alter any state in history, just clean messages in history. The `` `Commit All``` looks like me to update information in store or something like that. The current idea for `` `Commit All``` is the same think / action to clear history? It's not clear to me.

**Comment by mikaelhadler** [comment]
@Akryum Hey dude, any considerations about that?

**Comment by Akryum** [comment]
I still don't see the difference with `Commit All`...

**Comment by mikaelhadler** [comment]
So, that's okay : ], i'm close this PR, thanks for the reply

**Pull request closed without merging**
