### PR TITLE
499 Invalid prop definition crash

### LINKED ISSUE #499: Cannot read property 'type' of null
OS : Ubuntu 16.04
Chrome : 63.0.3239.84
vue : 2.5.13
vuex : 3.0.1
vue-devtools: 4.0.0

No content is appeared at right side, when I click on a component to inspect it. 
After I click on a component to inspect it, there are also a lot of errors in my console.

Please look at these two images below.

image

image

### PR DESCRIPTION
**Pull request by Akryum**
Fix #499

### CODE REVIEW

**Comment by Akryum** [comment]
It looks like vee-validate is doing quite weird things with props. I added a guard against invalid prop definitions. This is so edgy I don't know if it's really the devtools that should have fix for this or vee-validate. Thoughts @yyx990803?

**Comment by Akryum** [comment]
@logaretm ⬆️

**Comment by Akryum** [comment]
Also, the issue doesn't seems related to provide/inject.

**Comment by logaretm** [comment]
I can provide a fix on my end. But what is considered an invalid prop? vee-validate adds mostly adds data/computed fields to the components in the `beforeCreated` hook.

And there is the `fields` object which is consistently being updated since the props depend directly on the vnodes currently present in the template.

**Comment by logaretm** [comment]
@Akryum My guess is correct. The `fields` property seems to be the culprit here:

```js
this.$options.computed[options.fieldsBagName || 'fields'] = function fieldBagGetter () {
  if (!Object.keys(this.$validator.flags).length) {
    return fakeFlags;
  }
  return this.$validator.flags;
};
```
The check `Object.keys(this.$validator.flags).length` provides a temporary fallback for the fields until they are present after the directives have been bound to prevent undefined or null access crashes.

Removing the check fixes the issue in my local tests. I can push a release quickly and I would appreciate it if you can point out violations that are being done by vee-validate so I can address them too.

**Comment by Akryum** [comment]
From what I understand, `fields` looks like a Vue component and the devtools are now displaying components in the inspector. But the `$options.props` object of `fields` is invalid (each prop definition minimal form is `myProp: { type: null }`.

**Comment by Akryum** [comment]
Also, the name resolved for it is something like `<{ "dirty": false, "valid": true, ... }>`.

**Comment by logaretm** [comment]
But it isn't a component nor a prop, is it? so to clarify It just looks like one and gets interpreted as one and this caused the issue.

**Comment by Akryum** [comment]
We check if `object._isVue` is `true` and we treat it as a component then.

**Pull request closed without merging**
