### PR TITLE
Update readme.md:

### PR DESCRIPTION
**Pull request by smilingkite**
how to run ./node_modules/@vue/devtools/server.js

### CODE REVIEW

**Comment by Akryum** [comment]
`./node_modules/.bin/vue-devtools` is the correct way to run the program.

You can also use `npx vue-devtools` in your project root.

**Comment by smilingkite** [comment]
Thanks 'npx vue-devtools' did work for me. 

The first one perhaps needs to be run someplace else? For newbies to electron & this sort of tool a more elaborate explanation on the readme would be good.

**Comment by smilingkite** [comment]
This is the setup I ended up using for our local project. Feel free to use in readme.md:

http://www.hesselinkwebdesign.nl/2019/vue-dev-tools-for-development-in-ie-11/

**Comment by Akryum** [comment]
I guess it's because your are on Windows that directly running the file doesn't work?

**Comment by smilingkite** [comment]
Possibly? I don't know. But yes, I'm on Windows.

**Pull request closed without merging**
