### PR TITLE
Component inspector header static

### PR DESCRIPTION
**Pull request by anteriovieira**
Keep header static.

Before: 
header-before

After:
header-after

### CODE REVIEW

**Comment by posva** [comment]
I think it will be better to have the filter and inspect button right-aligned by letting the component name take the remaining space

**Comment by posva** [comment]
btw, why does the selected tab marker looks off for you?

**Comment by anteriovieira** [comment]
I'll show the image with your suggestions, and then I'll fix the pull request.

> btw, why does the selected tab marker looks off for you?

I've added a margin to improve the preview of the gif, but I'll avoid doing that.

**Comment by anteriovieira** [comment]
Organize the items in the action header

## Updates

- Right-aligned buttons
- Space for title

header-after-organize

- Press ESC to close import
- Right-aligned buttons
- Maybe add the type as title?

press-esc

**Pull request merged**
