### PR TITLE
#773: Fix payload on replaying mutation

### LINKED ISSUE #773: Vuex state not loading
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 68.0.3440.106, Mac OS X 10.13.5

### Steps to reproduce
Open an application, have some mutations happen. Inspect one and you'll see "Loading State" and it never changes.

Clicking Export of state will give `"__vue_devtool_undefined__"` to the clipboard.

It is also not working when in "Recording state" and you click "Load state"

### What is expected?
To view the full state at the time of the inspection.

### What is actually happening?
Mutation is visible, but the state as a whole is not.

image

### LINKED ISSUE #792: Time travel passes state instead of payload
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 69 / OSX 10.13.6

### Steps to reproduce
 - open https://new-issue.vuejs.org/?repo=vuejs/vue-devtools
 - click the button twice
 - time travel to first mutation
 - time travel to second mutation
 - check console

### What is expected?
State changes as per the mutation code

### What is actually happening?
Mutation is called with state as payload

### LINKED ISSUE #802: Vuex panel display state recursively
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 70.0.3538.67 / Mac OS X 10.13

### Steps to reproduce
Apologies if I can't offer clearer reproduction steps.
I was using Vue devtools 4.1.5 beta, and switched to 5.0.0.beta 3 to get Vuex mutations on init (https://github.com/vuejs/vue-devtools/pull/723).
Since switching, my state is displayed recursively in the Vuex panel.

### What is expected?
State correspond to actual store state. (this is what is looks like in **4.1.5 beta**)
capture d ecran 2018-10-17 a 16 01 20

### What is actually happening?
State is shown recursively. At the end of a mutation, the state is shown as still "recording"? (this is what is looks like in **5.0.0.beta 3**)
capture d ecran 2018-10-17 a 16 02 44
Once I click the button, the state look like this:
capture d ecran 2018-10-17 a 16 03 09

### Details
This is what my state looks like when I hit the export button in **4.1.5 beta**:
```
{
  "loading": false,
  "annotable": "gid://elite/Project/14",
  "notes": {
    "notes": [
      {
        "id": 1,
        "body": "some text.\nSome more text.",
        "createdAt": "2018-10-11T16:04:19.117-04:00",
        "updatedAt": "2018-10-12T16:04:51.489-04:00",
        "user": {
          "id": 336,
          "name": "N S",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/1?locale=fr"
      },
      {
        "id": 2,
        "body": "Hello!\n\nBye!",
        "createdAt": "2018-10-11T16:04:19.117-04:00",
        "updatedAt": "2018-10-12T16:04:44.359-04:00",
        "user": {
          "id": 336,
          "name": "N S",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/2?locale=fr"
      },
      {
        "id": 3,
        "body": "a brand new note!",
        "createdAt": "2018-10-12T15:20:13.090-04:00",
        "updatedAt": "2018-10-12T15:20:13.090-04:00",
        "user": {
          "id": 336,
          "name": "N S",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/3?locale=fr"
      },
      {
        "id": 5,
        "body": "Nouvelle note from JP edited",
        "createdAt": "2018-10-12T16:39:55.575-04:00",
        "updatedAt": "2018-10-12T16:42:57.025-04:00",
        "user": {
          "id": 325,
          "name": "A B",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/5?locale=fr"
      },
      {
        "id": 7,
        "body": "test test\ntest",
        "createdAt": "2018-10-12T18:37:57.620-04:00",
        "updatedAt": "2018-10-16T17:46:29.152-04:00",
        "user": {
          "id": 325,
          "name": "A B",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/7?locale=fr"
      },
      {
        "id": 8,
        "body": "Brand new note",
        "createdAt": "2018-10-16T17:47:32.018-04:00",
        "updatedAt": "2018-10-16T17:47:32.018-04:00",
        "user": {
          "id": 325,
          "name": "A B",
          "email": "redacted"
        },
        "url": "http://localhost:3000/notes/8?locale=fr"
      }
    ],
    "model": {}
  }
}
```
This is what the state looks like when I export state in **5.0.0.beta 3**
```
[
  {
    "loading": 1,
    "annotable": 0,
    "notes": 2
  },
  false,
  {
    "notes": 0,
    "model": 3
  },
  {}
]
```
 

Let me know if I can provide more details.

### PR DESCRIPTION
**Pull request by Sp1ker**
closes #773 , closes #792, closes #802 
All handlers are `wrappedMutationHandler ` with only 1 argument - `payload`

### CODE REVIEW

**Comment by Binaryify** [comment]
Finally it can work now~

**Comment by nhynes** [comment]
+1

**Comment by tochoromero** [comment]
I built this branch and I got the same results :(
The state does not load, it just stays in "Loading State" forever.

**Comment by davidpelayo** [comment]
@tochoromero it could be an issue with your store shape. It happened the same to me. It was an issue on my side with the usage of the `Vue.i18n` plugin. I did built this branch and works fine for me.

**Comment by tochoromero** [comment]
@davidpelayo I'm not using `Vue.i18n`, my store is pretty vanilla, other than using dynamic modules

**Comment by davidpelayo** [comment]
Is this at any point going to be merged?

**Comment by ellisio** [comment]
We have a rather complex dynamic module store and this branch allowed the devtools to start working again for us. Would be awesome to get this merged so I can reinstall the official package.

**Comment by iamareebjamal** [comment]
Guys, please merge this as debugging has become very difficult for us without this fix.

**Pull request merged**
