### PR TITLE
DarkTheme: Input text color

### LINKED ISSUE #1335: When the theme is dark or high contrast, the text in the edit box is invisible.
### Version
6.0.0-beta.3

### Browser and OS info
Chrome, Win10

### Steps to reproduce
1.Open a vue 3 project and set the theme of dev-tools to dark or high contrast.<br/>
2.Select any text to edit.

### What is expected?
The text in the edit box is visible.

### What is actually happening?
The text in the edit box is invisible.
image

### PR DESCRIPTION
**Pull request by ygj6**
Closes #1335

### CODE REVIEW

**Comment by Akryum** [comment]
Thanks! Why putting red text though?

**Comment by ygj6** [comment]
Because I found that the font color itself is red.

**Comment by ygj6** [comment]
image

**Comment by Akryum** [comment]
Thank you for the PR! The issue was closed already.

**Pull request closed without merging**
