### PR TITLE
Add routing tab

### PR DESCRIPTION
**Pull request by armano2**
This pull request contains changes from https://github.com/vuejs/vue-devtools/pull/272

TODO:
- [ ] Missed node update when page is already loaded (without dev tools)
- [ ] Missing function: `router.mode`
- [ ] Add unit tests
- [ ] There is no way to colapse nested routes
- [ ] Active route is not selected

image
image

Do not merge this pull request its not fully ready yet, but please review it and tell me if i'm doing this right.

### CODE REVIEW

**Comment by michalsnik** [comment]
Hey @armano2 are you going to work on this? I see it's been a long time now since the last change and it's a really exciting feature :)

**Comment by Akryum** [comment]
#726

**Comment by parreirat** [comment]
@michalsnik you can use the beta here, am currently using: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg

**Comment by armano2** [comment]
ohh i completely forgot about this xd
sorry

**Pull request closed without merging**
