### PR TITLE
[Typescript] added type definitions

### PR DESCRIPTION
**Pull request by karanisverma**
I have added type def for connect.
Issue: https://github.com/vuejs/vue-devtools/issues/779

### CODE REVIEW

**Comment by karanisverma** [comment]
@Akryum Why this PR is not getting Merged? Please let me know if there is something which need to be fixed here.

**Comment by yoyoys** [comment]
I think set port to `number|string` is better.

**Comment by karanisverma** [comment]
sure will make this change! Thanks @yoyoys

**Comment by karanisverma** [comment]
@posva  does these changes looks good ?

**Comment by posva** [comment]
I don't know. I haven't followed dev tools dev since @Akryum picked them up. I didn't know you could install DevTools as a package now. He will look at it whenever he has time. But to be honest this looks like low priority compared to buy GA and features so it may take a while

**Comment by karanisverma** [comment]
Thanks @posva 🙂

**Comment by championswimmer** [comment]
@Akryum 
This seems good to be merged. Very minor anyway. The types are all correct.

**Pull request merged**
