### PR TITLE
adds mutation filtering to Vuex tab

### PR DESCRIPTION
**Pull request by bartlomieju**
I guess this feature has been requested several times already  (#134, #112 ), so went ahead and implemented it. It allows to use both simple string search and RegExes. Appropriate error is displayed if RegEx can't be compiled.

vue-devtools

Unfortunately I couldn't get tests to start, so I did not write any. I'll try to do that but any help would be appreciated.

### CODE REVIEW

**Comment by yyx990803** [comment]
Nice! I tested locally and it's working great. But ideally we still want tests. What errors are you getting from `npm test`?

**Comment by bartlomieju** [comment]
Actually none... It hangs on 'Running:  vue-devtools e2e tests'. Sometimes it doesn't open browser, sometimes it does but with url 'data:;' and sometimes it opens actuall dev server but tests are not running. It deleted and re-installed whole package several times with no luck. Later I'll try to purge Java on my machine.

**Comment by yyx990803** [comment]
hmm... ok, I'll merge and add tests later, thanks!

**Comment by davidmoshal** [comment]
@bartlomieju thanks!

**Pull request merged**
