### PR TITLE
Editable fields

### LINKED ISSUE #74: Edit State Properties in Tree View
Do you plan to have a feature to edit the state right there in the app / tree view, right now it just displays the values but you can't edit them.

### PR DESCRIPTION
**Pull request by Akryum**
Fix #74

- [x] Some fields of component local state are editable
- [x] Warning if JSON is invalid
- [x] Edit values inside arrays and objects
- [x] Add items in arrays and objects
- [x] Remove items in arrays and objects
- [x] Edit the full array or object
- [x] Autocomplete special values (maybe they can be formatted with a contenteditable instead of an input)
- [x] Quick Edit for booleans: toggle `true`/`false`
- [x] Quick Edit for numbers: +1/-1 (with keyboard modifiers)

More types (RegExp + Dates) can be enabled after #474 is merged

vue-devtools-edit

vue-devtools-edit2

vue-devtools-edit3

### CODE REVIEW

**Comment by Akryum** [comment]
vue-devtools-edit4

**Comment by Akryum** [comment]
vue-devtools-edit5

**Comment by Akryum** [comment]
vue-devtools-edit6

**Comment by Akryum** [comment]
capture d ecran du 2017-12-27 19 59 00

**Comment by Akryum** [comment]
capture d ecran du 2017-12-27 20 18 06

**Comment by Akryum** [comment]
capture d ecran du 2017-12-27 20 37 09

**Comment by Akryum** [comment]
capture d ecran du 2017-12-27 21 28 41

**Comment by crswll** [comment]
Dude. Awesome.

**Comment by Akryum** [comment]
capture d ecran du 2017-12-28 03 04 44

capture d ecran du 2017-12-28 03 05 31

**Comment by Ben52** [comment]
Wow this is LIT
And I'm loving apollo-vue.

**Comment by DannyFeliz** [comment]
Dude, this is amazing

**Comment by posva** [comment]
This is clearly the best one 😄 

For the increment/decrement controls on numbers, there are the same problems as with collapse/expand. Control-click won't work in mack, so it should be cmd + click

**Comment by posva** [comment]
By testing a bit I found this behaviour:

screenflow

Adding multiple elements to an array adds first undefined, then the special value used for devtools

**Comment by Akryum** [comment]
This is all fixed! Also, I changed 'Alt' to 'Option' key on Mac for the relevant tooltips.

**Comment by gonzaloserrano** [comment]
Hi there, I'm using 4.1.4 and I'm not beeing able to edit anything inside the chrome vuex panel. I'm using Vue 2.5.13.

screenshot 2018-03-16 12 28 11

Any hints?

**Comment by Akryum** [comment]
@gonzaloserrano Vuex state is not editable at this time. This is planned though (and you can open a feature request in another issue 😉).

**Comment by gonzaloserrano** [comment]
OK, I thought this issue was exactly about implementing this. Thanks for your quick response!

**Comment by lloydjatkinson** [comment]
Will this be added to Vuex?

**Comment by Akryum** [comment]
Yes, and it's done: https://github.com/vuejs/vue-devtools/releases/tag/v5.0.0-beta.1

**Pull request merged**
