### PR TITLE
Workaround for Firefox - steps to install vue-devtools in Firefox

### PR DESCRIPTION
**Pull request by neeravp**
Chrome Store Foxified extension with Firefox Developer Edition enables to install vue-devtools in Firefox Developer Edition. I have written the steps to get vue-devtools working in Firefox Developer Edition with Chrome Store Foxified.

### CODE REVIEW

**Comment by posva** [comment]
ping @yyx990803 , tested and worked

**Comment by altitudems** [comment]
Confirmed to work well.

**Comment by andreicristianpetcu** [comment]
Or you can just provide a [link to download from](https://andreicristianpetcu.github.io/chrome2firefox/addons/vuejs_devtools-3.1.2-an+fx.xpi).

Please sign the addon and offer an official version. Chrome Store Foxified is for addon developers not for users.

**Comment by andreicristianpetcu** [comment]
If you wish to host your own addon you need to provide a special Content-Type with the vaule `application/x-xpinstall`. [Github pages](https://pages.github.com/) does this by default.

If you have issues with "duplicate extension ID" then you need to replace the ID in the manifest with a new UUID. 

`json
    "applications": {                                                                                                                                                                                                
        "gecko": {                                                                                                                                                                                                   
            "id": "nhdogjmejiglipccpnnnanhbledajbpd@chrome-store-foxified-unsigned"                                                                                                                                  
        }                                                                                                                                                                                                            
    }
`
with something like 
`json
    "applications": {                                                                                                                                                                                                
        "gecko": {                                                                                                                                                                                                   
            "id": "{57139B66-10D1-11E7-9FAB-1EC5A0406E17}"                                                                                                                                  
        }                                                                                                                                                                                                            
    }
`
The IDs can be generated from [here](http://www.somacon.com/p113.php) or with plain old GNU Bash `echo` ```uuidgen``` | head -c-1`. Don't forget the `{}` in `{57139B66-10D1-11E7-9FAB-1EC5A0406E17}`.

If you wish to sign the addon as part of your build you can use [web-ext sign](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign).

What I posted above is an unlisted addon. More info [here](https://blog.mozilla.org/addons/2017/01/26/mixing-listed-and-unlisted-on-amo/) and the review policies are [here](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews).

Please provide a listed addon. One that appears in [AMO](https://addons.mozilla.org). :D

**Comment by neeravp** [comment]
@andreicristianpetcu Thank you for the detailed explanation. I was wondering about the Id part but was unable to figure out how to tackle. So then I thought that for the time being let the users create their own id by signing the extension for their own use.

**Comment by andreicristianpetcu** [comment]
Just be sure that if you change the ID then Firefox will see it as a different addon. So try to pick an UUID and stick with it. You can use different ones if you have issues while signing it the first time.

**Pull request merged**
