### PR TITLE
Support regex

### LINKED ISSUE #276: RegExp are displayed as empty objects
In the component properties pane, Regex are not displayed:

image

To reproduce: add a data or computed property that holds a Regex.

What's expected: displaying the Regex

image

### PR DESCRIPTION
**Pull request by posva**
Closes #276

Add support for native types like Regexp. To add a new native type (eg: Symbol), we have to update the replacer function in util

It looks like:
screen shot 2017-05-10 at 15 40 31

screen shot 2017-05-10 at 15 41 35

Which is the same colour of the devtools

### CODE REVIEW

**Comment by posva** [comment]
The main problem was that the data being serialised, the regexp information is lost upon stringification. Therefore, the regex case is handled in the replacer that keeps the string representation of the regex in a custom format. This very same format can be used with `Symbols` and maybe others

**Comment by armano2** [comment]
I like your code way more 👍 
> To add a new native type (eg: Symbol)

```js
function replacer (key, val) {
  if (val === undefined) {
    return UNDEFINED
  } else if (val === Infinity) {
    return INFINITY
  } else if (val instanceof RegExp) {
    // special handling of native type
    return `[object RegExp ${val.toString()}]`
  } else if (typeof val === 'symbol') {
    return `[object Symbol ${val.toString()}]`
  } else {
    return sanitize(val)
  }
}

**Comment by posva** [comment]
Now that I think of it, it doesn't make sense to have `object` in the string there, it may be better to have something like `native` or `special` or `custom`

**Comment by armano2** [comment]
Right now most of build in types are "printed" as Object() and i think we should support them.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects

**Comment by posva** [comment]
The NaN display is actually a bug. I'll take a look

**Comment by posva** [comment]
Turned out it wasn't being handled

**Pull request merged**
