### PR TITLE
Remember initial mutations

### LINKED ISSUE #408: Vue Devtools not capturing initial vuex commits
Hi.

I have a simple application which fetches users on initialization. This uses the `FETCH_USERS` action and commits the mutation `USERS_FETCHED` when done. I never see this commit in the devtools, presumably because the devtools are not ready yet.

In the example below I use setTimeout to wait 500ms. Then the commit always shows in the devtools. 

It would be very nice if this could be avoided. Am I doing something wrong? The same problem is referenced here: https://github.com/vuejs/vue-devtools/issues/124 however the issue was closed with the message that the devtools should be open, then the page should be refreshed. But it doesn't solve the problem.

This is my `main.js`, which dispatches the action that doesn't show up as a commit:

```js
import Vue from "vue";
import VueRouter from "vue-router";
import Vuex from "vuex";

import { FETCH_USERS } from "./store";

import styles from "./styles.css";
import routes from "./routes";

import Application from "./components/Application";
import store from "./store";

Vue.use(VueRouter);

const router = new VueRouter({
  mode: "history",
  routes
});

new Vue({
  el: "#app",
  store,
  render: h => h(Application),
  router,
  created() {
    this.$store.dispatch(FETCH_USERS);
  }
});
```

if I change the initialisation to the following, the initial event is captured.

```js

setTimeout(
  () =>
    new Vue({
      el: "#app",
      store,
      render: h => h(Application),
      router,
      created() {
        this.$store.dispatch(FETCH_USERS);
      }
    }),
  500
);
```

Can I fix this in some way?

Oh, and by the way, I'm running Chrome 61.

Thanks for your great work!

screenshot from 2017-09-11 13-51-53

---

repro:

```html
<html>
<head>
  <title>Welcome to Vue</title>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/vuex"></script>
</head>
<body>
  <div id="app">
  </div>

  <script>
  function webRequest() {
    return {username: 'vuejs-hackman'};
  }
  var store = new Vuex.Store({
    state: {
      user: {}
    },
    mutations: {
      STORE_DATA(state, payload) {
        console.log('irun');
        window.localStorage.setItem("user", JSON.stringify(payload));
        state.user = payload;
      }
    },
    actions: {
      loadUser: function (ctx, payload) {
        ctx.commit('STORE_DATA', payload)
      }
    }
  });

  var app = new Vue({
    el: '#app',
    store: store,
    methods: {
      initUser: function(user) {
        // this.$store.commit('STORE_DATA', user);
        this.$store.dispatch('loadUser', webRequest());
      },
      loadUser: function() {
        // this.$store.dispatch('loadUser', webRequest());
        this.$store.commit('STORE_DATA', {user:'hi'});
      }
    },
    template: '<button @click="loadUser">click</button>',
    created: function() {
      const user = window.localStorage.getItem("user");
      if (user) {
        this.initUser(JSON.parse(user));
      }
    }
  })
  </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by simplesmiler**
Fixes #408.
This is alternative to #491, that does not require any changes to Vuex.

### CODE REVIEW

**Comment by bartlomieju** [comment]
I really like the idea it requires not changes to Vuex!

**Comment by EmmanuelDemey** [comment]
This fix is already available ? Which version should we use ?

**Comment by Akryum** [comment]
5.x beta

**Comment by EmmanuelDemey** [comment]
Thanks

**Pull request merged**
